import Head from "next/head";
import Chart from "~/components/Chart";
import { api } from "~/utils/api";

export default function Home() {
  const datasetsQuery = api.fetch.fetchDatasets.useQuery();
  console.log(datasetsQuery.data);
  // const dataMutation = api.fetc
  return (
    <>
      <Head>
        <title>City Data</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            City <span className="text-[hsl(280,100%,70%)]">Data</span> App
          </h1>
          <div className="flex flex-col gap-4">
            <div className="flex w-full justify-center gap-4">
              {Array.from({ length: 2010 - 2005 + 1 }, (_, i) => (
                <div
                  className="rounded-lg bg-white px-1 hover:cursor-pointer hover:bg-[hsl(280,100%,70%)]"
                  key={2005 + i}
                >
                  {2005 + i}
                </div>
              ))}
            </div>
            <div className="flex flex-wrap gap-2">
              {datasetsQuery.data?.map((dataset) => (
                <div
                  key={dataset.id}
                  className="rounded-lg bg-white px-2 hover:cursor-pointer hover:bg-[hsl(280,100%,70%)]"
                >
                  {dataset.state}
                </div>
              ))}
            </div>
          </div>
          <div className="flex h-96 w-full grid-cols-1 items-center justify-center">
            <Chart />
          </div>
        </div>
      </main>
    </>
  );
}
